# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0354791e7fbe60f6f84b8ed6b4564832b74a7faba40d31a65bf69071ed8760580d58afe44561063374051b4cd1ac9e33f69098dce73fa911fce1eb068f07c92a

test:
  secret_key_base: fee133eacc8a29caba801d64064ca29492169d532970b485838202593eec7c72da0128e93eb4ecd144cf1e2258348071b95c533d3d15c9c577b19106e59e0a4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
